;invalid instructions, should not be highlighted
broadcast/vvbroadcast
cmovnpo/cmovpos
cvtsi2pi/cvtps2ps/cvtsi2si/cvtpi2pi/cvtss2ss/cvtss2ps/cvtss2pi/cvtpi2ss
cvttdq2ps
cvttsi2si/cvttps2ps/cvttpi2pi
cwdqo
fbst
fcmovnbu
fiaddp/fisubp
ficomip/ficompp
fidivp/fidivrp
fimulp
fisubp/fisubrp
fucomipp
loopn
outsq
paddub/padduw
padduw
pmovsx/pmovzx
pmovsxww
popd/popq/popfdq
prefetcht3/prefetchta
psubuw
punpckhw/vpunpckhw
rccps
repn
sald/sard
vbroadcast
vcvttusi2sd/vcvttusi2ss
vfmaddsubsd/vfnmaddsubpd
vfmsubadd132sd/vfmsubadd132ss/vfnmsubadd132pd
vfnmaddsub213pd
vgatherds/vgatherdpq/vpgatherdqpd
vmovbe
vmovdq2q/vmovq2dq
vmovnti/vmovntq
vmovsx/vmovsxd
vmovzx
vmul
vpbroadcastm
vpmaskmov
vpopcnt
vppcmpnlt
vpshldv
vpshrd
vpshrdv
vpshufw
xrdfsbase
xwait/iwait