CCMPB CCMPBE CCMPF CCMPL CCMPLE CCMPNB CCMPNBE CCMPNL CCMPNLE CCMPNO CCMPNS CCMPNZ CCMPO CCMPS CCMPT CCMPZ
CFCMOVB CFCMOVBE CFCMOVL CFCMOVLE CFCMOVNB CFCMOVNBE CFCMOVNL CFCMOVNLE CFCMOVNO CFCMOVNP CFCMOVNS CFCMOVNZ CFCMOVO CFCMOVP CFCMOVS CFCMOVZ
CMPBEXADD CMPBXADD CMPLEXADD CMPLXADD CMPNBEXADD CMPNBXADD CMPNLEXADD CMPNLXADD CMPNOXADD CMPNPXADD CMPNSXADD CMPNZXADD CMPOXADD CMPPXADD CMPSXADD CMPZXADD
CTESTB CTESTBE CTESTF CTESTL CTESTLE CTESTNB CTESTNBE CTESTNL CTESTNLE CTESTNO CTESTNS CTESTNZ CTESTO CTESTS CTESTT CTESTZ
ENQCMD ENQCMDS JMPABS MOVDIR64B MOVDIRI
POP2 POP2P PUSH2 PUSH2P
LDTILECFG STTILECFG TILELOADD TILELOADDT1 TILESTORED
WRSSD WRSSQ WRUSSD WRUSSQ



invalid:
ccmpnf ccmpnt cfcmovze cmpnpexadd ctestnf